### PR TITLE
More colors and entropy

### PR DESCRIPTION
**Pull request by alexvandesande**
We are using Blockies on our project (Ethereum Mist) and these are the changes we worked on:
- Changed the random seed generator. We found that the current code was limited to 65536 icons, which means that according to the birthday paradox after 300 icons we'd have a 50% chance of a collision (which goes up to 99% after 1000 icons). This means of course that it will break backwards compatibility as all icons generated by this new package will be different than the same previous
- Added an optional third "spot color". Each icon has a 13% chance of being this third color. This lesser common color creates structures that resemble eyes, mouths etc
- Made the background color random unless set.
- Changed the randomness of the color generation so it fits the whole colorspace but prefers colors in the middle of the lightness spectre

### CODE REVIEW

**Comment by download13** [comment]
Sorry, I didn't see this a month ago for some reason.

I'd like to maintain the look of the icons generated by the library as it is now, but the new additions look pretty cool as well.

How about I add a link to your repo as an alternative style?

**Comment by alexvandesande** [comment]
I totally understand your point. Having icons not change is the main point of the library, but the low entropy of the current library was a deal breaker for our use.

Do it as you please, your work was very useful for our code and the least I could do to thank you was contribute back with our improvements.

Thanks!

**Comment by download13** [comment]
Greater entropy would be good to have. It's okay if the icons change, I just meant I wanted to keep the same general aesthetic for them.

It is the replacement prng that allows for increased entropy or are the changes to the way it calculates colors also necessary?

**Comment by alexvandesande** [comment]
The secondary and spot colors are optional. In my repo I've made the background color random by default but that it can be set to white, but you can switch that preference.

If you set the backgroundColor to #FFF and spot color to -1 then it will have the same basic look as it has currently, but if you prefer I can make these options default.

**Comment by farhankhwaja** [comment]
Hey Guys, I have a question, does the Color of icons matter?? As in, (correct me if I am wrong) the icons generated for an address is always the same, but how about the color. Can the color change but the pattern remains the same??

below is an example:
- I ported the JS library to C# Unity and got the below results:

image

 The above icon generated has the same shape and pattern only the color is different.

**Comment by alexvandesande** [comment]
Yes, the colors do matter quite a bit, as far as ethereum address identicons are concerned. They're the first thing a user will notice. Notice that the color logic used in ethereum is very different than download13's original implementation

**Comment by farhankhwaja** [comment]
Thanks Alex. Hmm. I will need to check th color logic for Ethereum. Can you point me to where I should be looking for "Ethereum Color logic"?

**Comment by alexvandesande** [comment]
@farhankhwaja  check here: https://github.com/ethereum/blockies

**Comment by farhankhwaja** [comment]
@alexvandesande this link has the same implementation as yours.

**Comment by alexvandesande** [comment]
Yes, that is mine. But you are posting on download13's GitHub

**Pull request merged**
